### ISSUE TITLE
Invalid Base32 Character with 2factor authentication

### ISSUE THREAD

**Issue by jlntrt** [inwx/ruby-client#4]
Hey there,

In my INWX account I activated the "mobile TAN" method or basically 2factor authentication. When I try to authenticate with 
```ruby
user = 'xy'
pass = '123'
shared_secret = '123 456'
INWX::Domrobot.new.set_language('en').use_ote.use_json.set_debug(true).login(user, pass, shared_secret)
```

I get the following error:
```
/home/julian/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rotp-5.1.0/lib/rotp/base32.rb:70:in `decode_quint': Invalid Base32 Character - '0' (ROTP::Base32::Base32Error)
        from /home/julian/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rotp-5.1.0/lib/rotp/base32.rb:18:in `block in decode'
        from /home/julian/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rotp-5.1.0/lib/rotp/base32.rb:16:in `each'
        from /home/julian/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rotp-5.1.0/lib/rotp/base32.rb:16:in `decode'
        from /home/julian/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rotp-5.1.0/lib/rotp/otp.rb:49:in `byte_secret'
        from /home/julian/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rotp-5.1.0/lib/rotp/otp.rb:27:in `generate_otp'
        from /home/julian/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rotp-5.1.0/lib/rotp/totp.rb:24:in `now'
        from /home/julian/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/inwx-domrobot-3.1/lib/inwx-domrobot.rb:132:in `get_secret_code'
        from /home/julian/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/inwx-domrobot-3.1/lib/inwx-domrobot.rb:71:in `login'
        from domain_check.rb:10:in `<main>'
```

Can you reproduce this issue?

**Comment by jlntrt** [comment]
Workaround by adding the [Base32](https://github.com/stesla/base32) gem and encoding the shared secret:
```ruby
require 'base32'
shared_secret = Base32.encode '343 786'
# ...
```

**Comment by givemelight** [comment]
Actually this is very misleading because the library works as expected.

The `shared_secret` parameter expects the (already) base32 encoded shared secret that is shown when you activate *mobile TAN*. The library uses this key to generate a one time password, this means the library itself becomes the "Authenticator App".

If you want to submit the mobile TAN itself from your own Authenticator App, you need to change

    secret_code = get_secret_code(shared_secret)
    ret = call('account', 'unlock', tan: secret_code)

to

    ret = call('account', 'unlock', tan: shared_secret)

and pass the one time password without spaces to the login method.
